name: Program Registration
on:
  workflow_dispatch:
  schedule:
    - cron: "15 4 * * 1,3"
    # Sunday/Tuesday 8:30PM PST Registration Time (we are 8 hours behind UTC)
    # Run workflow a few minutes earlier to ensure we can register right on time
    # May need to adjust for Daylight Savings later
jobs:
  register:
    name: Register
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Access credentials
        run: echo '${{ secrets.CYPRESS_ENV }}' > cypress.env.json
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Upload screenshots if failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - name: Upload videos if failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
